# -*- coding: utf-8 -*-
"""strokedetector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18dF5Fiz9eBbi3p6A9b95QpxN7t3zpOWd

#Face Recognization

##Import and setup
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# streamlit
# torch
# torchvision
# torchaudio
# pillow
# numpy
# opencv-python

import os
import shutil
from sklearn.model_selection import train_test_split

#!pip install kagglehub
import kagglehub
path = kagglehub.dataset_download("danish003/face-images-of-acute-stroke-and-non-acute-stroke")
main_dir = os.path.join(path, "main")
stroke_dir = os.path.join(main_dir, "stroke_data")
nostroke_dir = os.path.join(main_dir, "noStroke_data")

# Output path for writable split data
output_dir = "/kaggle/working/splits"
os.makedirs(output_dir, exist_ok=True)

print(f"✅ Using dataset from: {path}")
print(f"✅ Saving new splits to: {output_dir}")

# List images
stroke_images = [os.path.join(stroke_dir, f) for f in os.listdir(stroke_dir) if f.lower().endswith(('.jpg', '.png', '.jpeg'))]
nostroke_images = [os.path.join(nostroke_dir, f) for f in os.listdir(nostroke_dir) if f.lower().endswith(('.jpg', '.png', '.jpeg'))]

# Balance classes to 1000 each
stroke_images = stroke_images[:1000]
nostroke_images = nostroke_images[:1000]

# Labels
images = stroke_images + nostroke_images
labels = [1]*len(stroke_images) + [0]*len(nostroke_images)

# Split into train (70%), val (15%), test (15%)
X_temp, X_test, y_temp, y_test = train_test_split(images, labels, test_size=0.15, stratify=labels, random_state=42)
X_train, X_val, y_train, y_val = train_test_split(X_temp, y_temp, test_size=0.1765, stratify=y_temp, random_state=42)
# (0.1765 of 85% ≈ 15%)

print(f"✅ Train: {len(X_train)}, Val: {len(X_val)}, Test: {len(X_test)}")

# Helper to copy files
def copy_files(file_list, label_list, subset_name):
    for img_path, label in zip(file_list, label_list):
        label_name = "stroke" if label == 1 else "noStroke"
        dest_dir = os.path.join(output_dir, subset_name, label_name)
        os.makedirs(dest_dir, exist_ok=True)
        shutil.copy(img_path, dest_dir)

copy_files(X_train, y_train, "train")
copy_files(X_val, y_val, "val")
copy_files(X_test, y_test, "test")

print("✅ Dataset successfully split and saved to /kaggle/working/splits")

"""##CNN Model"""

import torch.nn as nn
import torch.nn.functional as F

class StrokeCNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 16, 3)
        self.pool = nn.MaxPool2d(2)
        self.fc1 = nn.Linear(16 * 111 * 111, 2)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = x.view(-1, 16 * 111 * 111)
        x = self.fc1(x)
        return x

model = StrokeCNN()

import torch
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

split_dir = "/kaggle/working/splits"

transform = transforms.Compose([
    transforms.Resize((224, 224)),   # keep 224 like your earlier pattern
    transforms.ToTensor()
])

train_dataset = datasets.ImageFolder(root=os.path.join(split_dir, "train"), transform=transform)
val_dataset   = datasets.ImageFolder(root=os.path.join(split_dir, "val"),   transform=transform)
test_dataset  = datasets.ImageFolder(root=os.path.join(split_dir, "test"),  transform=transform)

batch_size = 32
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
val_loader   = DataLoader(val_dataset,   batch_size=batch_size, shuffle=False)
test_loader  = DataLoader(test_dataset,  batch_size=batch_size, shuffle=False)

print("Classes:", train_dataset.classes)
print("Samples -> train:", len(train_dataset), "val:", len(val_dataset), "test:", len(test_dataset))

"""##Train"""

import torch.optim as optim

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

epochs = 7
for epoch in range(epochs):
    model.train()
    running_loss = 0.0
    correct = 0
    total = 0

    for images, labels in train_loader:
        images, labels = images.to(device), labels.to(device)
        outputs = model(images)
        loss = criterion(outputs, labels)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        running_loss += loss.item()
        _, predicted = torch.max(outputs, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

    acc = 100 * correct / total
    print(f"Epoch [{epoch+1}/{epochs}] Loss: {running_loss:.3f} | Accuracy: {acc:.2f}%")

"""##Valid"""

from sklearn.metrics import precision_score, recall_score, f1_score

model.eval()
correct = 0
total = 0
y_true = []
y_pred = []

with torch.no_grad():
    for images, labels in val_loader:
        images, labels = images.to(device), labels.to(device)
        outputs = model(images)
        _, predicted = torch.max(outputs, 1)

        total += labels.size(0)
        correct += (predicted == labels).sum().item()

        y_true.extend(labels.cpu().numpy())
        y_pred.extend(predicted.cpu().numpy())

# Metrics
val_accuracy = 100 * correct / total
val_precision = precision_score(y_true, y_pred, average='binary') * 100
val_recall = recall_score(y_true, y_pred, average='binary') * 100
val_f1 = f1_score(y_true, y_pred, average='binary') * 100

print(f"✅ Validation Accuracy: {val_accuracy:.2f}%")
print(f"✅ Validation Precision: {val_precision:.2f}%")
print(f"✅ Validation Recall: {val_recall:.2f}%")
print(f"✅ Validation F1-score: {val_f1:.2f}%")

#confusion matrix
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

model.eval()
y_pred_list = []
y_true_list = []

with torch.no_grad():
    for images, labels in val_loader:
        images, labels = images.to(device), labels.to(device)
        outputs = model(images)
        _, predicted = torch.max(outputs, 1)
        y_pred_list.extend(predicted.cpu().numpy())
        y_true_list.extend(labels.cpu().numpy())

cm = confusion_matrix(y_true_list, y_pred_list)
plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=val_dataset.classes, yticklabels=val_dataset.classes)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Stroke Detection Confusion Matrix")
plt.show()

torch.save(model.state_dict(), "stroke_model.pth")

import streamlit as st
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import cv2
from PIL import Image
import os

# ------------------------------
# Model Definition
# ------------------------------
class StrokeCNN(nn.Module):
    def __init__(self):
        super(StrokeCNN, self).__init__()
        self.conv1 = nn.Conv2d(3, 16, 3, padding=1)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(16, 32, 3, padding=1)
        self.fc1 = nn.Linear(32 * 56 * 56, 128)
        self.fc2 = nn.Linear(128, 2)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(-1, 32 * 56 * 56)
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x


# ------------------------------
# Load Trained Model
# ------------------------------
@st.cache_resource
def load_model():
    model = StrokeCNN()
    model_path = "stroke_model.pth"
    if not os.path.exists(model_path):
        st.error(f"❌ Model file '{model_path}' not found! Please place it in the same folder.")
        st.stop()
    model.load_state_dict(torch.load(model_path, map_location=torch.device("cpu")))
    model.eval()
    return model


model = load_model()

st.title(" Stroke Detection App")
st.markdown("Upload an **image or video**.")

option = st.radio("Select Input Type:", ["Image", "Video"])

# ------------------------------
# Image Upload Section
# ------------------------------
if option == "Image":
    image_file = st.file_uploader("Upload an image", type=["jpg", "jpeg", "png"])

    if image_file:
        image = Image.open(image_file).convert("RGB")
        st.image(image, caption="Uploaded Image", use_column_width=True)

        img = np.array(image.resize((224, 224))) / 255.0
        img_tensor = torch.tensor(img).permute(2, 0, 1).unsqueeze(0).float()

        with torch.no_grad():
            outputs = model(img_tensor)
            probabilities = torch.softmax(outputs, dim=1).numpy()[0]
            prediction = np.argmax(probabilities)
            confidence = probabilities[prediction]

        label = "Stroke Detected 🧠" if prediction == 1 else "No Stroke Detected ✅"
        st.markdown(f"### Prediction: **{label}**")
        st.markdown(f"### Confidence: **{confidence * 100:.2f}%**")

        # Optionally save the result
        save_option = st.checkbox("💾 Save result to file")
        if save_option:
            with open("stroke_results.txt", "a") as f:
                f.write(f"Image: {image_file.name}, Prediction: {label}, Confidence: {confidence:.4f}\n")
            st.success("✅ Result saved to 'stroke_results.txt'.")


# ------------------------------
# Video Upload Section
# ------------------------------
elif option == "Video":
    video_file = st.file_uploader("Upload a video", type=["mp4", "avi", "mov"])
    if video_file:
        temp_video = "temp_video.mp4"
        with open(temp_video, "wb") as f:
            f.write(video_file.read())

        cap = cv2.VideoCapture(temp_video)
        frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
        stframe = st.empty()

        stroke_frames = 0
        total_frames = 0

        while cap.isOpened():
            ret, frame = cap.read()
            if not ret:
                break
            total_frames += 1

            frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            img = cv2.resize(frame_rgb, (224, 224)) / 255.0
            img_tensor = torch.tensor(img).permute(2, 0, 1).unsqueeze(0).float()

            with torch.no_grad():
                outputs = model(img_tensor)
                prediction = torch.argmax(outputs, dim=1).item()
                if prediction == 1:
                    stroke_frames += 1

            stframe.image(frame_rgb, caption=f"Frame {total_frames}/{frame_count}", use_column_width=True)

        cap.release()

        st.success("Video processed successfully!")
        stroke_prob = (stroke_frames / total_frames) * 100
        st.markdown(f"### Stroke Frame Percentage: **{stroke_prob:.2f}%**")

        if stroke_prob > 50:
            st.error("High possibility of stroke signs detected in this video!")
        else:
            st.info("Low likelihood of stroke signs detected.")

        # Save summary
        with open("stroke_results.txt", "a") as f:
            f.write(f"Video: {video_file.name}, Stroke Frame %: {stroke_prob:.2f}\n")
        st.success("Summary saved to 'stroke_results.txt'.")